services:
  jwt-auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: moodboard/jwt-auth:latest
    container_name: jwt-auth
    ports:
      - 4000:4000
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: auth_db
    networks:
      - mysql_default
    deploy:
      resources:
        reservations:
          cpus: '0.25'
          memory: 30M
        limits:
          cpus: '0.5'
          memory: 50M

networks:
  mysql_default:
    driver: bridge
