version: '3.9'

services:
  jwt-auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: moodboard/jwt-auth
    container_name: jwt-auth
    ports:
      - 4000:4000
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: auth_db
    networks:
      - auth-network
    depends_on:
      - mysql
    # deploy:
    #   resources:
    #     reservations:
    #       cpus: '0.25'
    #       memory: 30M
    #     limits:
    #       cpus: '0.5'
    #       memory: 50M

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth_db
    volumes:
      - auth:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/data_dump.sql
    networks:
      - auth-network

volumes:
  auth: {}

networks:
  auth-network:
    driver: bridge
