GET http://192.168.100.14:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6InRva2VuIn0.eyJ1c2VySWQiOjEsIm5hbWUiOiJXYWh5dSIsImVtYWlsIjoiZXhhbXBsZUBnbWFpbC5jb20iLCJpYXQiOjE3NTE5NDU0MTQsImV4cCI6MTc1MTk0NTQ3NCwiaXNzIjoidG9rZW4ifQ.L4hWBjcJV1UHafz3CnUIP8Ldp7Pi8mWtpuGj9DtYLU4
###
POST http://192.168.100.14:4000/users
Content-Type: application/json

{
    "name": "Jamal",
    "email" : "example1@gmail.com",
    "password": "123456",
    "confPassword": "123456"
}

###
POST http://192.168.100.14:4000/login
Content-Type: application/json

{
    "email" : "example1@gmail.com",
    "password": "123456"
}

###
GET http://192.168.100.14:4000/token

###
DELETE http://localhost:4000/logout